//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverTurtle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Snippits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Snippits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilverTurtle.Resources.Snippits", typeof(Snippits).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKCOL.
        /// </summary>
        internal static string cmbBackColor {
            get {
                return ResourceManager.GetString("cmbBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENCOL.
        /// </summary>
        internal static string cmbForeColor {
            get {
                return ResourceManager.GetString("cmbForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIRCLE ?.
        /// </summary>
        internal static string DrawCircle {
            get {
                return ResourceManager.GetString("DrawCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENCOL BLACK
        ///BACKCOL CRIMSON
        ///REPEAT 36 [ RT 10 REPEAT 360 [FD 1 RT 1 WAIT 2]].
        /// </summary>
        internal static string DrawCircles {
            get {
                return ResourceManager.GetString("DrawCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO PETAL X 
        ///[ 
        ///FD 20
        ///REPEAT 10 
        ///[ 
        ///RIGHT 20 FD 2 
        ///] 
        ///FD 20 
        ///] 
        ///
        ///PENWIDTH 2
        ///RIGHT 180
        ///FORWARD 50
        ///RIGHT 180
        ///
        ///PENCOL BLUE
        ///RIGHT 90
        ///FORWARD 150
        ///RIGHT 180
        ///FORWARD 300
        ///RIGHT 180
        ///PU
        ///FORWARD 150
        ///PD
        ///LEFT 90
        ///
        ///LEFT 10
        ///PENCOL GREEN
        ///
        ///REPEAT 3
        ///[
        ///  FORWARD 100
        ///  RIGHT 180
        ///  PU 
        ///  FORWARD 100
        ///  PD
        ///  RIGHT 180
        ///  RIGHT 10
        ///]
        ///
        ///LEFT 20
        ///FD 120
        ///
        ///PENCOL RED
        ///
        ///LEFT 90
        ///REPEAT 10
        ///[
        ///  DO PETAL 1
        ///]
        ///
        ///PENWIDTH 3
        ///
        ///PENCOL LIGHTGREEN
        ///
        ///PU
        ///FORWARD -2
        ///PD
        ///
        ///REPEAT 18
        ///[
        ///  FORWARD 1
        ///  RI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrawFlower {
            get {
                return ResourceManager.GetString("DrawFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO GASKET1 X N
        ///[ 
        /// IF X &lt; N [STOP]
        ///DIVIDE X 2
        /// REPEAT 3 [DO GASKET1 X N FD X RT 120]
        ///]
        ///
        ///TO GASKET X N
        ///[
        /// CS PU BK 30 LT 90 FD 200 RT 90 PD
        /// DO GASKET1 X N
        ///]
        ///PENCOL PURPLE
        ///DO GASKET1 512 512
        /// DO GASKET1 512 256
        /// DO GASKET1 512 128
        /// DO GASKET1 512 64
        /// DO GASKET1 512 32
        /// DO GASKET1 512 16.
        /// </summary>
        internal static string DrawGasket {
            get {
                return ResourceManager.GetString("DrawGasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORWARD ?.
        /// </summary>
        internal static string DrawLine {
            get {
                return ResourceManager.GetString("DrawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO SPIRAL SIZE
        ///[
        ///   IF  SIZE &gt; 30 [STOP] 
        ///   FD SIZE RT 15   
        ///  MULTIPLY SIZE 1.02
        ///  DO SPIRAL SIZE 
        ///]
        ///DO SPIRAL 10.
        /// </summary>
        internal static string DrawSpiral {
            get {
                return ResourceManager.GetString("DrawSpiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQUARE ?.
        /// </summary>
        internal static string DrawSquare {
            get {
                return ResourceManager.GetString("DrawSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO SYCAMORE2 :X
        ///[ 
        ///WAIT 5
        ///IF :X &lt; 12 [STOP]
        /// FD X
        /// SET TEMP X
        ///MULTIPLY TEMP 0.7
        /// RT 25 
        ///DO SYCAMORE2 TEMP
        ///SET TEMP X
        ///MULTIPLY TEMP 0.6
        /// LT 25 
        ///DO SYCAMORE2 TEMP
        ///SET TEMP X
        ///MULTIPLY TEMP 0.7
        /// LT 28 
        ///DO SYCAMORE2 TEMP
        /// RT 28 BK X
        ///]
        ///
        ///TO SYCAMORE1 X
        ///[ 
        ///pu home pd
        ///BACKCOL LIGHTSKYBLUE
        ///PENCOL DARKGREEN 
        ///PU BK 300 PD
        ///DO SYCAMORE2 X
        /// ]
        ///
        ///TO FOREST DUMMY
        /// [
        ///PU HOME FD 500 PD
        /// DO SYCAMORE1 150
        ///]
        ///DO FOREST DUMMY.
        /// </summary>
        internal static string DrawTree {
            get {
                return ResourceManager.GetString("DrawTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIANGLE ?.
        /// </summary>
        internal static string DrawTriangle {
            get {
                return ResourceManager.GetString("DrawTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO &lt;funcname&gt; ? 
        ///[
        ///].
        /// </summary>
        internal static string FunctionCommand {
            get {
                return ResourceManager.GetString("FunctionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEAT ?
        ///[
        ///].
        /// </summary>
        internal static string RepeatLoop {
            get {
                return ResourceManager.GetString("RepeatLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHILE ? OP ?
        ///[
        ///].
        /// </summary>
        internal static string WhileLoop {
            get {
                return ResourceManager.GetString("WhileLoop", resourceCulture);
            }
        }
    }
}
